In [1]:
import tensorflow as tf
import numpy as np

In [2]:
wav_ph = tf.placeholder(tf.float32,[None,10])
is_training_ph = tf.placeholder(tf.bool)

In [3]:
sess = tf.InteractiveSession()

In [38]:
bn = tf.contrib.slim.batch_norm(wav_ph,is_training=is_training_ph,decay=0.9)

In [39]:
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)

In [40]:
wavs = np.stack([np.ones((10),np.float32),np.zeros((10),np.float32),np.arange(10,dtype=np.float32)])

In [41]:
sess.run(tf.global_variables_initializer())

In [162]:
sess.run([bn,update_ops],{wav_ph:wavs,is_training_ph:True})

[array([[ 1.41104233,  0.70552105,  0.        , -0.26717538, -0.39216444,
         -0.46286044, -0.50796366, -0.53913563, -0.56192929, -0.5793063 ],
        [-0.70552123, -1.41104221, -1.22382736, -1.06870151, -0.98041099,
         -0.92572087, -0.8889364 , -0.86261702, -0.84289396, -0.82758039],
        [-0.70552123,  0.70552105,  1.22382736,  1.3358767 ,  1.37257528,
          1.38858128,  1.39689994,  1.40175259,  1.40482318,  1.40688658]], dtype=float32),
 [array([ 0.33333334,  0.66666669,  1.        ,  1.33333337,  1.66666675,
          2.        ,  2.33333349,  2.66666675,  3.        ,  3.33333349], dtype=float32),
  array([  0.33333331,   0.33333337,   1.        ,   2.33333349,
           4.33333349,   7.00000048,  10.33333397,  14.33333302,
          19.        ,  24.33333588], dtype=float32),
  array([ 0.33333334,  0.66666669,  1.        ,  1.33333337,  1.66666675,
          2.        ,  2.33333349,  2.66666675,  3.        ,  3.33333349], dtype=float32),
  array([  0.33333331,